// <auto-generated />
using System;
using HO.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HO.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HO.Domain.Entities.Store", b =>
            {
                b.Property<Guid>("StoreId").HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWSEQUENTIALID()");
                b.Property<string>("StoreCode").HasMaxLength(20).HasColumnType("nvarchar(20)");
                b.Property<string>("StoreName").HasMaxLength(100).HasColumnType("nvarchar(100)");
                b.Property<string>("Region").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Zone").HasMaxLength(50).HasColumnType("nvarchar(50)");
                b.Property<string>("Status").HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Active");
                b.Property<string>("FYCloseStatus").HasMaxLength(20).HasColumnType("nvarchar(20)").HasDefaultValue("Pending");
                b.Property<bool>("IsDeleted").HasColumnType("bit").HasDefaultValue(false);
                b.Property<DateTime>("CreatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<DateTime>("UpdatedAt").HasColumnType("datetime2").HasDefaultValueSql("GETUTCDATE()");
                b.Property<string>("CreatedBy").HasMaxLength(100).HasColumnType("nvarchar(100)").HasDefaultValue("SYSTEM");
                b.HasKey("StoreId");
                b.ToTable("Stores");
            });
#pragma warning restore 612, 618
        }
    }
}
